from .builder.point import Point
from .builder.line import Line
from .base.shape import Shape
from .figures.rectangle import Rectangle
from .figures.square import Square
from .figures.triangle import Triangle
from .figures.isoceles import Isoceles
from .figures.scalene import Scalene
from .figures.equilateral import Equilateral
from .figures.trirectangle import TriRectangle